version: "3.5"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    
    networks:
      - dbnet
    ports: 
    - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=service_C#
  calculator:
    build: .
    depends_on:
      - mssql
    networks:
      - dbnet
    links:
      - mssql:mssql

networks:
  dbnet:
    driver: bridge

    
      
        

           